[package]
name = "reduceit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ducere = { path = "../" }
syn = "1.0"
tracing-subscriber = { version = "0.3.2", features = ["env-filter"] }